### ISSUE TITLE
How to use the .ckpt models

### ISSUE THREAD

**Issue by djokester** [iro-cp/FCRN-DepthPrediction#54]
The download link given here -> [NYU-FCRN.ckpt](http://campar.in.tum.de/files/rupprecht/depthpred/NYU_FCRN-checkpoint.zip)  provides us with a zip folder. Upon extraction, the folder contains three files 
NYU_FCRN.ckpt.index  
NYU_FCRN.ckpt.data-00000-of-00001  
NYU_FCRN.ckpt.meta

The documentation reads that the predict.py can be used with the model NYU_FCRN.ckpt as follows
`python predict.py NYU_FCRN.ckpt yourimage.jpg`
Which of the three files are we supposed to consider as the NYU_FCRN.ckpt?

**Comment by kartk** [comment]
Just use NYU_FCRN.ckpt . Need not specify which file to use

**Comment by djokester** [comment]
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for NYU_FCRN
.ckpt

**Comment by chrirupp** [comment]
I guess this is solved

**Comment by Nilay27** [comment]
@chrirupp  this issue is not yet solved for me. NYU_FCRN.ckpt still throws the error : 

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for NYU_FCRN.ckpt 

and it should as there is no such file, rather we have a folder named NYU_FCRN-checkpoint, which contains three files
NYU_FCRN.ckpt.index
NYU_FCRN.ckpt.data-00000-of-00001
NYU_FCRN.ckpt.meta

how to run this code properly? because running it with any of these three files throws an error: 

DataLossError (see above for traceback): Unable to open table file NYU_FCRN-checkpoint/NYU_FCRN.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
